# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagina_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_home(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 50, 800, 150))
        self.widget_2.setStyleSheet("QWidget{\n"
"background: #03A9F4;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.bem_vindo = QtWidgets.QLabel(self.widget_2)
        self.bem_vindo.setGeometry(QtCore.QRect(40, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bem_vindo.setFont(font)
        self.bem_vindo.setStyleSheet("QLabel{\n"
"color: #FFFFFF}")
        self.bem_vindo.setObjectName("bem_vindo")
        self.nome_fulano = QtWidgets.QLabel(self.widget_2)
        self.nome_fulano.setGeometry(QtCore.QRect(160, 40, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.nome_fulano.setFont(font)
        self.nome_fulano.setStyleSheet("QLabel{\n"
"color: #FFFFFF}")
        self.nome_fulano.setObjectName("nome_fulano")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 51))
        self.widget.setStyleSheet("QWidget{\n"
"background:#0265CB\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.prof_button_bar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.prof_button_bar.sizePolicy().hasHeightForWidth())
        self.prof_button_bar.setSizePolicy(sizePolicy)
        self.prof_button_bar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.prof_button_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.prof_button_bar.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 10px 0px 10px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tool_bar/icons8-professor-18.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.prof_button_bar.setIcon(icon)
        self.prof_button_bar.setIconSize(QtCore.QSize(20, 20))
        self.prof_button_bar.setObjectName("prof_button_bar")
        self.horizontalLayout.addWidget(self.prof_button_bar)
        self.turma_button_bar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.turma_button_bar.sizePolicy().hasHeightForWidth())
        self.turma_button_bar.setSizePolicy(sizePolicy)
        self.turma_button_bar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.turma_button_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.turma_button_bar.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 10px 0px 10px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/tool_bar/icons8-primeiro-plano-do-grupo-selecionado-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.turma_button_bar.setIcon(icon1)
        self.turma_button_bar.setIconSize(QtCore.QSize(20, 20))
        self.turma_button_bar.setObjectName("turma_button_bar")
        self.horizontalLayout.addWidget(self.turma_button_bar)
        self.aluno_button_bar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aluno_button_bar.sizePolicy().hasHeightForWidth())
        self.aluno_button_bar.setSizePolicy(sizePolicy)
        self.aluno_button_bar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.aluno_button_bar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.aluno_button_bar.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 10px 0px 10px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/tool_bar/icons8-pessoa-do-sexo-masculino-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.aluno_button_bar.setIcon(icon2)
        self.aluno_button_bar.setIconSize(QtCore.QSize(20, 18))
        self.aluno_button_bar.setObjectName("aluno_button_bar")
        self.horizontalLayout.addWidget(self.aluno_button_bar)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.config_button_bar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_button_bar.sizePolicy().hasHeightForWidth())
        self.config_button_bar.setSizePolicy(sizePolicy)
        self.config_button_bar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.config_button_bar.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 0xp 0px 5px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/tool_bar/icons8-configuração-18 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config_button_bar.setIcon(icon3)
        self.config_button_bar.setIconSize(QtCore.QSize(17, 16))
        self.config_button_bar.setObjectName("config_button_bar")
        self.horizontalLayout.addWidget(self.config_button_bar)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 230, 680, 300))
        self.tableWidget.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.tableWidget.setStyleSheet("QTableWidget{\n"
"background:#FFFFFF}")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(50, 149, 700, 411))
        self.widget_3.setStyleSheet("QWidget{\n"
"background:#FFFFFF;\n"
"border-radius:2px;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.search_icon = QtWidgets.QLabel(self.widget_3)
        self.search_icon.setGeometry(QtCore.QRect(10, 60, 30, 30))
        self.search_icon.setStyleSheet("image: url(:/principal/icons8-pesquisar-20 (1).png);")
        self.search_icon.setText("")
        self.search_icon.setObjectName("search_icon")
        self.buscar_input = QtWidgets.QPushButton(self.widget_3)
        self.buscar_input.setGeometry(QtCore.QRect(520, 60, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_input.setFont(font)
        self.buscar_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buscar_input.setStyleSheet("QPushButton{\n"
"background: #3C4252;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.buscar_input.setCheckable(False)
        self.buscar_input.setAutoExclusive(False)
        self.buscar_input.setObjectName("buscar_input")
        self.adicionar_button = QtWidgets.QPushButton(self.widget_3)
        self.adicionar_button.setGeometry(QtCore.QRect(520, 20, 161, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_button.setFont(font)
        self.adicionar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_button.setStyleSheet("QPushButton{\n"
"background: #33CD33;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/principal/icons8-soma-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.adicionar_button.setIcon(icon4)
        self.adicionar_button.setIconSize(QtCore.QSize(30, 30))
        self.adicionar_button.setObjectName("adicionar_button")
        self.search_input = QtWidgets.QPlainTextEdit(self.widget_3)
        self.search_input.setGeometry(QtCore.QRect(40, 60, 461, 31))
        self.search_input.setStyleSheet("QPlainTextEdit{\n"
"font-size:16px;\n"
"border-bottom: 1px solid #999A9A }")
        self.search_input.setObjectName("search_input")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 100, 680, 300))
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"background:#FFFFFF;\n"
"border: 1px solid #CCC}")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home"))
        self.bem_vindo.setText(_translate("MainWindow", "Bem Vindo"))
        self.nome_fulano.setText(_translate("MainWindow", "Fulano"))
        self.prof_button_bar.setText(_translate("MainWindow", "  Professor"))
        self.turma_button_bar.setText(_translate("MainWindow", "  Turma"))
        self.aluno_button_bar.setText(_translate("MainWindow", "  Aluno"))
        self.config_button_bar.setText(_translate("MainWindow", "  Configuração"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome Completo"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cpf"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Disciplina"))
        self.buscar_input.setText(_translate("MainWindow", "Buscar"))
        self.adicionar_button.setText(_translate("MainWindow", " Adicionar"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Digite um nome a ser pesquisado"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome Completo"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cpf"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Telefone"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Disciplina"))
import principal
import toolBar


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_home()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
