# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registro_professor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_register_professor(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 598)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background:#F4F4F4;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 800, 51))
        self.widget.setStyleSheet("QWidget{\n"
"background:#0265CB\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: #FFF;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 80, 741, 491))
        self.frame.setStyleSheet("QFrame{\n"
"background:#FFF;\n"
"border-radius:15px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.nomeC_text_input = QtWidgets.QLabel(self.frame)
        self.nomeC_text_input.setGeometry(QtCore.QRect(20, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nomeC_text_input.setFont(font)
        self.nomeC_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.nomeC_text_input.setObjectName("nomeC_text_input")
        self.nome_input = QtWidgets.QLineEdit(self.frame)
        self.nome_input.setGeometry(QtCore.QRect(20, 50, 701, 41))
        self.nome_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.nome_input.setObjectName("nome_input")
        self.email_text_input = QtWidgets.QLabel(self.frame)
        self.email_text_input.setGeometry(QtCore.QRect(20, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.email_text_input.setFont(font)
        self.email_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.email_text_input.setObjectName("email_text_input")
        self.email_imput = QtWidgets.QLineEdit(self.frame)
        self.email_imput.setGeometry(QtCore.QRect(20, 140, 455, 41))
        self.email_imput.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.email_imput.setText("")
        self.email_imput.setObjectName("email_imput")
        self.cpf_text_input = QtWidgets.QLabel(self.frame)
        self.cpf_text_input.setGeometry(QtCore.QRect(20, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cpf_text_input.setFont(font)
        self.cpf_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.cpf_text_input.setObjectName("cpf_text_input")
        self.cpf_input = QtWidgets.QLineEdit(self.frame)
        self.cpf_input.setGeometry(QtCore.QRect(20, 230, 215, 41))
        self.cpf_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.cpf_input.setText("")
        self.cpf_input.setObjectName("cpf_input")
        self.estadoC_text_input = QtWidgets.QLabel(self.frame)
        self.estadoC_text_input.setGeometry(QtCore.QRect(20, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.estadoC_text_input.setFont(font)
        self.estadoC_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.estadoC_text_input.setObjectName("estadoC_text_input")
        self.estadoC_comboB = QtWidgets.QComboBox(self.frame)
        self.estadoC_comboB.setGeometry(QtCore.QRect(20, 320, 215, 41))
        self.estadoC_comboB.setStyleSheet("QComboBox{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.estadoC_comboB.setObjectName("estadoC_comboB")
        self.estadoC_comboB.addItem("")
        self.estadoC_comboB.addItem("")
        self.estadoC_comboB.addItem("")
        self.endereco_text_input = QtWidgets.QLabel(self.frame)
        self.endereco_text_input.setGeometry(QtCore.QRect(20, 370, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.endereco_text_input.setFont(font)
        self.endereco_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.endereco_text_input.setObjectName("endereco_text_input")
        self.endereco_input = QtWidgets.QLineEdit(self.frame)
        self.endereco_input.setGeometry(QtCore.QRect(20, 410, 455, 41))
        self.endereco_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.endereco_input.setText("")
        self.endereco_input.setObjectName("endereco_input")
        self.sexo_text_input = QtWidgets.QLabel(self.frame)
        self.sexo_text_input.setGeometry(QtCore.QRect(490, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sexo_text_input.setFont(font)
        self.sexo_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.sexo_text_input.setObjectName("sexo_text_input")
        self.sexo_ComboB = QtWidgets.QComboBox(self.frame)
        self.sexo_ComboB.setGeometry(QtCore.QRect(490, 140, 230, 41))
        self.sexo_ComboB.setStyleSheet("QComboBox{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.sexo_ComboB.setObjectName("sexo_ComboB")
        self.sexo_ComboB.addItem("")
        self.sexo_ComboB.addItem("")
        self.sexo_ComboB.addItem("")
        self.nasc_text_input = QtWidgets.QLabel(self.frame)
        self.nasc_text_input.setGeometry(QtCore.QRect(490, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.nasc_text_input.setFont(font)
        self.nasc_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.nasc_text_input.setObjectName("nasc_text_input")
        self.nasc_input = QtWidgets.QLineEdit(self.frame)
        self.nasc_input.setGeometry(QtCore.QRect(490, 230, 230, 41))
        self.nasc_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.nasc_input.setObjectName("nasc_input")
        self.rg_text_input = QtWidgets.QLabel(self.frame)
        self.rg_text_input.setGeometry(QtCore.QRect(250, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.rg_text_input.setFont(font)
        self.rg_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.rg_text_input.setObjectName("rg_text_input")
        self.nasc_input_2 = QtWidgets.QLineEdit(self.frame)
        self.nasc_input_2.setGeometry(QtCore.QRect(250, 230, 225, 41))
        self.nasc_input_2.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.nasc_input_2.setObjectName("nasc_input_2")
        self.tel_text_input = QtWidgets.QLabel(self.frame)
        self.tel_text_input.setGeometry(QtCore.QRect(490, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.tel_text_input.setFont(font)
        self.tel_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.tel_text_input.setObjectName("tel_text_input")
        self.tel2_input = QtWidgets.QLineEdit(self.frame)
        self.tel2_input.setGeometry(QtCore.QRect(490, 320, 230, 41))
        self.tel2_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.tel2_input.setObjectName("tel2_input")
        self.cadastrar_button = QtWidgets.QPushButton(self.frame)
        self.cadastrar_button.setGeometry(QtCore.QRect(600, 410, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cadastrar_button.setFont(font)
        self.cadastrar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cadastrar_button.setStyleSheet("QPushButton{\n"
"background: #33CD33;\n"
"color: #FFF;\n"
"border-radius:4px;\n"
" text-align: center;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/principal/icons8-soma-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastrar_button.setIcon(icon)
        self.cadastrar_button.setIconSize(QtCore.QSize(25, 30))
        self.cadastrar_button.setObjectName("cadastrar_button")
        self.voltar_button = QtWidgets.QPushButton(self.frame)
        self.voltar_button.setGeometry(QtCore.QRect(490, 410, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.voltar_button.setFont(font)
        self.voltar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voltar_button.setStyleSheet("QPushButton{\n"
"color: #999A9A;\n"
"border: 1px solid #CCC;\n"
"border-radius:4px;\n"
"text-align: center;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cadastro/icons8-esquerda-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar_button.setIcon(icon1)
        self.voltar_button.setIconSize(QtCore.QSize(25, 30))
        self.voltar_button.setObjectName("voltar_button")
        self.materiaC_text_input_2 = QtWidgets.QLabel(self.frame)
        self.materiaC_text_input_2.setGeometry(QtCore.QRect(250, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.materiaC_text_input_2.setFont(font)
        self.materiaC_text_input_2.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.materiaC_text_input_2.setObjectName("materiaC_text_input_2")
        self.materia_comboB = QtWidgets.QComboBox(self.frame)
        self.materia_comboB.setGeometry(QtCore.QRect(250, 320, 225, 41))
        self.materia_comboB.setStyleSheet("QComboBox{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.materia_comboB.setObjectName("materia_comboB")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.email_text_input.raise_()
        self.nomeC_text_input.raise_()
        self.nome_input.raise_()
        self.email_imput.raise_()
        self.cpf_text_input.raise_()
        self.cpf_input.raise_()
        self.estadoC_text_input.raise_()
        self.estadoC_comboB.raise_()
        self.endereco_text_input.raise_()
        self.endereco_input.raise_()
        self.sexo_text_input.raise_()
        self.sexo_ComboB.raise_()
        self.nasc_text_input.raise_()
        self.nasc_input.raise_()
        self.rg_text_input.raise_()
        self.nasc_input_2.raise_()
        self.tel_text_input.raise_()
        self.tel2_input.raise_()
        self.cadastrar_button.raise_()
        self.voltar_button.raise_()
        self.materiaC_text_input_2.raise_()
        self.materia_comboB.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastre de professor"))
        self.label.setText(_translate("MainWindow", "  Cadastro de Professor"))
        self.nomeC_text_input.setText(_translate("MainWindow", "Nome completo *"))
        self.nome_input.setPlaceholderText(_translate("MainWindow", "Digite o nome completo"))
        self.email_text_input.setText(_translate("MainWindow", "E-mail *"))
        self.email_imput.setPlaceholderText(_translate("MainWindow", "Digite o e-mail"))
        self.cpf_text_input.setText(_translate("MainWindow", "CPF *"))
        self.cpf_input.setPlaceholderText(_translate("MainWindow", "Digite o CPF"))
        self.estadoC_text_input.setText(_translate("MainWindow", "Estado civil"))
        self.estadoC_comboB.setItemText(0, _translate("MainWindow", "Solteiro (a)"))
        self.estadoC_comboB.setItemText(1, _translate("MainWindow", "Casado (a)"))
        self.estadoC_comboB.setItemText(2, _translate("MainWindow", "Viúvo (a)"))
        self.endereco_text_input.setText(_translate("MainWindow", "Endereço  *"))
        self.endereco_input.setPlaceholderText(_translate("MainWindow", "Digite o endereço"))
        self.sexo_text_input.setText(_translate("MainWindow", "Sexo *"))
        self.sexo_ComboB.setItemText(0, _translate("MainWindow", "Masculino"))
        self.sexo_ComboB.setItemText(1, _translate("MainWindow", "Femino"))
        self.sexo_ComboB.setItemText(2, _translate("MainWindow", "Prefiro não informar"))
        self.nasc_text_input.setText(_translate("MainWindow", "Nascimento *"))
        self.nasc_input.setPlaceholderText(_translate("MainWindow", "Digite a data de nascimento"))
        self.rg_text_input.setText(_translate("MainWindow", "RG *"))
        self.nasc_input_2.setPlaceholderText(_translate("MainWindow", "Digite o rg"))
        self.tel_text_input.setText(_translate("MainWindow", "Telefone *"))
        self.tel2_input.setPlaceholderText(_translate("MainWindow", "Digite outro telefone"))
        self.cadastrar_button.setText(_translate("MainWindow", "Cadastrar"))
        self.voltar_button.setText(_translate("MainWindow", "Voltar"))
        self.materiaC_text_input_2.setText(_translate("MainWindow", "Matéria"))
        self.materia_comboB.setItemText(0, _translate("MainWindow", "Engenharia da Computação"))
        self.materia_comboB.setItemText(1, _translate("MainWindow", "Sistemas de Informação"))
        self.materia_comboB.setItemText(2, _translate("MainWindow", "Ciência da Computação"))
        self.materia_comboB.setItemText(3, _translate("MainWindow", "Análise e Desenvolvimento de Sistemas"))
import cadastro
import principal


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_register_professor()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
