# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(810, 600)
        Dialog.setStyleSheet("QDialog{\n"
"background: #FFF;\n"
"}\n"
"")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(220, 59, 370, 481))
        self.frame.setMinimumSize(QtCore.QSize(370, 481))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QFrame{\n"
"background: #FFFFFF;\n"
"border-radius:7px;\n"
"box-shadow: 10px 10px 40px rgba(0, 0, 0, 0.4);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.login_text = QtWidgets.QTextEdit(self.frame)
        self.login_text.setGeometry(QtCore.QRect(30, 20, 171, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.login_text.setFont(font)
        self.login_text.setReadOnly(True)
        self.login_text.setObjectName("login_text")
        self.nome_text_input = QtWidgets.QTextEdit(self.frame)
        self.nome_text_input.setGeometry(QtCore.QRect(30, 80, 111, 31))
        self.nome_text_input.setReadOnly(True)
        self.nome_text_input.setObjectName("nome_text_input")
        self.nome_input = QtWidgets.QLineEdit(self.frame)
        self.nome_input.setGeometry(QtCore.QRect(30, 110, 311, 41))
        self.nome_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.nome_input.setObjectName("nome_input")
        self.email_text_input = QtWidgets.QTextEdit(self.frame)
        self.email_text_input.setGeometry(QtCore.QRect(30, 160, 91, 31))
        self.email_text_input.setReadOnly(True)
        self.email_text_input.setObjectName("email_text_input")
        self.email_input = QtWidgets.QLineEdit(self.frame)
        self.email_input.setGeometry(QtCore.QRect(30, 190, 311, 41))
        self.email_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.email_input.setObjectName("email_input")
        self.cadastrar_button = QtWidgets.QPushButton(self.frame)
        self.cadastrar_button.setGeometry(QtCore.QRect(30, 420, 311, 41))
        self.cadastrar_button.setMinimumSize(QtCore.QSize(0, 41))
        self.cadastrar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cadastrar_button.setStyleSheet("QPushButton{\n"
" background-color: #f72585;\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    cursor: pointer;\n"
"    margin: 0;\n"
"}")
        self.cadastrar_button.setObjectName("cadastrar_button")
        self.nome_person_icon = QtWidgets.QLabel(self.frame)
        self.nome_person_icon.setGeometry(QtCore.QRect(310, 120, 20, 20))
        self.nome_person_icon.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-pessoa-do-sexo-masculino-100-1.png)\n"
"}\n"
"")
        self.nome_person_icon.setText("")
        self.nome_person_icon.setObjectName("nome_person_icon")
        self.nome_div_input = QtWidgets.QFrame(self.frame)
        self.nome_div_input.setGeometry(QtCore.QRect(300, 120, 1, 20))
        self.nome_div_input.setStyleSheet("Line{\n"
"background: #ccc}")
        self.nome_div_input.setFrameShape(QtWidgets.QFrame.VLine)
        self.nome_div_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.nome_div_input.setObjectName("nome_div_input")
        self.email_div_input = QtWidgets.QFrame(self.frame)
        self.email_div_input.setGeometry(QtCore.QRect(300, 200, 1, 20))
        self.email_div_input.setStyleSheet("Line{\n"
"background: #ccc}")
        self.email_div_input.setFrameShape(QtWidgets.QFrame.VLine)
        self.email_div_input.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.email_div_input.setObjectName("email_div_input")
        self.email_icon = QtWidgets.QLabel(self.frame)
        self.email_icon.setGeometry(QtCore.QRect(310, 200, 20, 20))
        self.email_icon.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-mensagem-20.png)\n"
"}\n"
"")
        self.email_icon.setText("")
        self.email_icon.setObjectName("email_icon")
        self.email_input_2 = QtWidgets.QLineEdit(self.frame)
        self.email_input_2.setGeometry(QtCore.QRect(30, 270, 311, 41))
        self.email_input_2.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.email_input_2.setObjectName("email_input_2")
        self.email_icon_2 = QtWidgets.QLabel(self.frame)
        self.email_icon_2.setGeometry(QtCore.QRect(310, 280, 20, 20))
        self.email_icon_2.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-mensagem-20.png)\n"
"}\n"
"")
        self.email_icon_2.setText("")
        self.email_icon_2.setObjectName("email_icon_2")
        self.email_text_input_2 = QtWidgets.QTextEdit(self.frame)
        self.email_text_input_2.setGeometry(QtCore.QRect(30, 240, 151, 31))
        self.email_text_input_2.setReadOnly(True)
        self.email_text_input_2.setObjectName("email_text_input_2")
        self.email_div_input_2 = QtWidgets.QFrame(self.frame)
        self.email_div_input_2.setGeometry(QtCore.QRect(300, 280, 1, 20))
        self.email_div_input_2.setStyleSheet("Line{\n"
"background: #ccc}")
        self.email_div_input_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.email_div_input_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.email_div_input_2.setObjectName("email_div_input_2")
        self.senha_icon = QtWidgets.QLabel(self.frame)
        self.senha_icon.setGeometry(QtCore.QRect(310, 360, 20, 20))
        self.senha_icon.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-cadeado-100.png);\n"
"}\n"
"")
        self.senha_icon.setText("")
        self.senha_icon.setObjectName("senha_icon")
        self.senha_input = QtWidgets.QLineEdit(self.frame)
        self.senha_input.setGeometry(QtCore.QRect(30, 350, 311, 41))
        self.senha_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.senha_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_input.setObjectName("senha_input")
        self.senha_text_input = QtWidgets.QTextEdit(self.frame)
        self.senha_text_input.setGeometry(QtCore.QRect(30, 320, 111, 31))
        self.senha_text_input.setReadOnly(True)
        self.senha_text_input.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.senha_text_input.setObjectName("senha_text_input")
        self.senha_div = QtWidgets.QFrame(self.frame)
        self.senha_div.setGeometry(QtCore.QRect(300, 360, 1, 20))
        self.senha_div.setStyleSheet("Line{\n"
"background: #ccc}")
        self.senha_div.setFrameShape(QtWidgets.QFrame.VLine)
        self.senha_div.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.senha_div.setObjectName("senha_div")
        self.close_button = QtWidgets.QPushButton(self.frame)
        self.close_button.setGeometry(QtCore.QRect(310, 30, 51, 31))
        self.close_button.setStyleSheet("QPushButton{\n"
"border:none;\n"
"}\n"
"")
        self.close_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/login/icons8-x-40.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close_button.setIcon(icon)
        self.close_button.setIconSize(QtCore.QSize(30, 30))
        self.close_button.setObjectName("close_button")
        self.senha_text_input.raise_()
        self.senha_input.raise_()
        self.email_text_input_2.raise_()
        self.login_text.raise_()
        self.nome_text_input.raise_()
        self.email_text_input.raise_()
        self.email_input.raise_()
        self.cadastrar_button.raise_()
        self.nome_input.raise_()
        self.nome_person_icon.raise_()
        self.nome_div_input.raise_()
        self.email_div_input.raise_()
        self.email_icon.raise_()
        self.email_input_2.raise_()
        self.email_icon_2.raise_()
        self.email_div_input_2.raise_()
        self.senha_icon.raise_()
        self.senha_div.raise_()
        self.close_button.raise_()
        self.background_blue = QtWidgets.QWidget(Dialog)
        self.background_blue.setGeometry(QtCore.QRect(0, 0, 810, 610))
        self.background_blue.setStyleSheet("QWidget{\n"
"background:#0265CB\n"
"}")
        self.background_blue.setObjectName("background_blue")
        self.background_blue.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login_text.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:696; color:#284658;\">Cadastre-se</span></p></body></html>"))
        self.nome_text_input.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">Nome</span></p></body></html>"))
        self.nome_input.setPlaceholderText(_translate("Dialog", "Digite seu nome completo"))
        self.email_text_input.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">E-mail</span></p></body></html>"))
        self.email_input.setPlaceholderText(_translate("Dialog", "Digite seu e-mail"))
        self.cadastrar_button.setText(_translate("Dialog", "CADASTRAR"))
        self.email_input_2.setPlaceholderText(_translate("Dialog", "Confirme seu e-mail"))
        self.email_text_input_2.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">Confirme o e-mail</span></p></body></html>"))
        self.senha_input.setPlaceholderText(_translate("Dialog", "Digite sua senha"))
        self.senha_text_input.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">Senha</span></p></body></html>"))
import telas.login


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
