# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regristro_de_turmas.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets



class Ui_register_turmas(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("QFrame{\n"
"background:#F4F4F4;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 51))
        self.widget.setStyleSheet("QWidget{\n"
"background:#0265CB\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"color: #FFF;\n"
"}")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(30, 80, 741, 491))
        self.frame.setStyleSheet("QFrame{\n"
"background:#FFF;\n"
"border-radius:15px;}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.turma_text_input = QtWidgets.QLabel(self.frame)
        self.turma_text_input.setGeometry(QtCore.QRect(30, 10, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.turma_text_input.setFont(font)
        self.turma_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.turma_text_input.setObjectName("turma_text_input")
        self.turma_input = QtWidgets.QLineEdit(self.frame)
        self.turma_input.setGeometry(QtCore.QRect(30, 50, 700, 41))
        self.turma_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.turma_input.setObjectName("turma_input")
        self.materia_text_input = QtWidgets.QLabel(self.frame)
        self.materia_text_input.setGeometry(QtCore.QRect(30, 100, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.materia_text_input.setFont(font)
        self.materia_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.materia_text_input.setObjectName("materia_text_input")
        self.materia_comboB = QtWidgets.QComboBox(self.frame)
        self.materia_comboB.setGeometry(QtCore.QRect(30, 140, 700, 41))
        self.materia_comboB.setStyleSheet("QComboBox{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.materia_comboB.setObjectName("materia_comboB")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.materia_comboB.addItem("")
        self.prof_text_input = QtWidgets.QLabel(self.frame)
        self.prof_text_input.setGeometry(QtCore.QRect(30, 190, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.prof_text_input.setFont(font)
        self.prof_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.prof_text_input.setObjectName("prof_text_input")
        self.prof_input = QtWidgets.QComboBox(self.frame)
        self.prof_input.setGeometry(QtCore.QRect(30, 230, 700, 41))
        self.prof_input.setStyleSheet("QComboBox{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.prof_input.setObjectName("prof_input")
        self.inicio_text_imput = QtWidgets.QLabel(self.frame)
        self.inicio_text_imput.setGeometry(QtCore.QRect(30, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inicio_text_imput.setFont(font)
        self.inicio_text_imput.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.inicio_text_imput.setObjectName("inicio_text_imput")
        self.inicio_date_edit = QtWidgets.QDateEdit(self.frame)
        self.inicio_date_edit.setGeometry(QtCore.QRect(30, 320, 210, 41))
        self.inicio_date_edit.setStyleSheet("QDateEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.inicio_date_edit.setObjectName("inicio_date_edit")
        self.termino_text_input = QtWidgets.QLabel(self.frame)
        self.termino_text_input.setGeometry(QtCore.QRect(260, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.termino_text_input.setFont(font)
        self.termino_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.termino_text_input.setObjectName("termino_text_input")
        self.termino_date_edit = QtWidgets.QDateEdit(self.frame)
        self.termino_date_edit.setGeometry(QtCore.QRect(260, 320, 210, 41))
        self.termino_date_edit.setStyleSheet("QDateEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.termino_date_edit.setObjectName("termino_date_edit")
        self.valor_text_input = QtWidgets.QLabel(self.frame)
        self.valor_text_input.setGeometry(QtCore.QRect(490, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.valor_text_input.setFont(font)
        self.valor_text_input.setStyleSheet("QLabel{\n"
"color:#999A9A;\n"
" font-weight: 600;}")
        self.valor_text_input.setObjectName("valor_text_input")
        self.valor_input = QtWidgets.QLineEdit(self.frame)
        self.valor_input.setGeometry(QtCore.QRect(490, 320, 241, 41))
        self.valor_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px\n"
"}")
        self.valor_input.setObjectName("valor_input")
        self.voltar_button = QtWidgets.QPushButton(self.frame)
        self.voltar_button.setGeometry(QtCore.QRect(500, 410, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.voltar_button.setFont(font)
        self.voltar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.voltar_button.setStyleSheet("QPushButton{\n"
"color: #999A9A;\n"
"border: 1px solid #CCC;\n"
"border-radius:4px;\n"
"text-align: center;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cadastro/icons8-esquerda-30.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.voltar_button.setIcon(icon)
        self.voltar_button.setIconSize(QtCore.QSize(25, 30))
        self.voltar_button.setObjectName("voltar_button")
        self.cadastrar_button = QtWidgets.QPushButton(self.frame)
        self.cadastrar_button.setGeometry(QtCore.QRect(610, 410, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.cadastrar_button.setFont(font)
        self.cadastrar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cadastrar_button.setStyleSheet("QPushButton{\n"
"background: #33CD33;\n"
"color: #FFF;\n"
"border-radius:4px;\n"
" text-align: center;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/principal/icons8-soma-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cadastrar_button.setIcon(icon1)
        self.cadastrar_button.setIconSize(QtCore.QSize(25, 30))
        self.cadastrar_button.setObjectName("cadastrar_button")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de turmas"))
        self.label.setText(_translate("MainWindow", "  Cadastro de Turma"))
        self.turma_text_input.setText(_translate("MainWindow", "Nome da turma *"))
        self.turma_input.setPlaceholderText(_translate("MainWindow", "Digite o nome completo"))
        self.materia_text_input.setText(_translate("MainWindow", "Matéria"))
        self.materia_comboB.setItemText(0, _translate("MainWindow", "Engenharia da Computação"))
        self.materia_comboB.setItemText(1, _translate("MainWindow", "Sistemas de Informação"))
        self.materia_comboB.setItemText(2, _translate("MainWindow", "Ciência da Computação"))
        self.materia_comboB.setItemText(3, _translate("MainWindow", "Análise e Desenvolvimento de Sistemas"))
        self.prof_text_input.setText(_translate("MainWindow", "Professor"))
        self.inicio_text_imput.setText(_translate("MainWindow", "Data de inicio"))
        self.termino_text_input.setText(_translate("MainWindow", "Data de termino"))
        self.valor_text_input.setText(_translate("MainWindow", "Valor total"))
        self.valor_input.setPlaceholderText(_translate("MainWindow", "Digite o valor do curso"))
        self.voltar_button.setText(_translate("MainWindow", "Voltar"))
        self.cadastrar_button.setText(_translate("MainWindow", "Cadastrar"))
import cadastro
import principal


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_register_turmas()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
