# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_login(object):
    def setupUi(self, Dialog_login):
        Dialog_login.setObjectName("Dialog_login")
        Dialog_login.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog_login.sizePolicy().hasHeightForWidth())
        Dialog_login.setSizePolicy(sizePolicy)
        Dialog_login.setStyleSheet("QDialog{\n"
"background: #FFF;\n"
"}")
        self.frame = QtWidgets.QFrame(Dialog_login)
        self.frame.setGeometry(QtCore.QRect(220, 59, 370, 481))
        self.frame.setMinimumSize(QtCore.QSize(370, 481))
        self.frame.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame.setStyleSheet("QFrame{\n"
"background: #FFFFFF;\n"
"border-radius:7px;\n"
"box-shadow: 10px 10px 40px rgba(0, 0, 0, 0.4);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setObjectName("frame")
        self.fixed_text = QtWidgets.QTextEdit(self.frame)
        self.fixed_text.setGeometry(QtCore.QRect(30, 80, 281, 51))
        self.fixed_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.fixed_text.setStyleSheet("QTextEdit{\n"
"background:#FFF\n"
"}")
        self.fixed_text.setReadOnly(True)
        self.fixed_text.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.fixed_text.setObjectName("fixed_text")
        self.login_text = QtWidgets.QTextEdit(self.frame)
        self.login_text.setGeometry(QtCore.QRect(30, 20, 121, 51))
        self.login_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.login_text.setReadOnly(True)
        self.login_text.setObjectName("login_text")
        self.email_text_input = QtWidgets.QTextEdit(self.frame)
        self.email_text_input.setGeometry(QtCore.QRect(30, 130, 111, 31))
        self.email_text_input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.email_text_input.setReadOnly(True)
        self.email_text_input.setObjectName("email_text_input")
        self.email_input = QtWidgets.QLineEdit(self.frame)
        self.email_input.setGeometry(QtCore.QRect(30, 160, 311, 41))
        self.email_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px;\n"
"}")
        self.email_input.setObjectName("email_input")
        self.senha_text_input = QtWidgets.QTextEdit(self.frame)
        self.senha_text_input.setGeometry(QtCore.QRect(30, 220, 111, 31))
        self.senha_text_input.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.senha_text_input.setReadOnly(True)
        self.senha_text_input.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.senha_text_input.setObjectName("senha_text_input")
        self.senha_input = QtWidgets.QLineEdit(self.frame)
        self.senha_input.setGeometry(QtCore.QRect(30, 250, 311, 41))
        self.senha_input.setStyleSheet("QLineEdit{\n"
"border-radius: 4px;\n"
"border: 1px solid #ccc;\n"
"padding-left:10px;\n"
"font-size:14px;\n"
"}")
        self.senha_input.setText("")
        self.senha_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senha_input.setObjectName("senha_input")
        self.esqueceu_senha_text = QtWidgets.QTextEdit(self.frame)
        self.esqueceu_senha_text.setGeometry(QtCore.QRect(30, 310, 171, 31))
        self.esqueceu_senha_text.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.esqueceu_senha_text.setReadOnly(True)
        self.esqueceu_senha_text.setObjectName("esqueceu_senha_text")
        self.entrar_button = QtWidgets.QPushButton(self.frame)
        self.entrar_button.setGeometry(QtCore.QRect(30, 360, 311, 41))
        self.entrar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.entrar_button.setStyleSheet("QPushButton{\n"
" background-color: #2079D5;\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    cursor: pointer;\n"
"    margin: 0;\n"
"}")
        self.entrar_button.setObjectName("entrar_button")
        self.cadastrar_button = QtWidgets.QPushButton(self.frame)
        self.cadastrar_button.setGeometry(QtCore.QRect(30, 420, 311, 41))
        self.cadastrar_button.setMinimumSize(QtCore.QSize(0, 41))
        self.cadastrar_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cadastrar_button.setStyleSheet("QPushButton{\n"
" background-color: #f72585;\n"
"    color: #fff;\n"
"    font-size: 16px;\n"
"    border-radius: 4px;\n"
"    font-weight: bold;\n"
"    cursor: pointer;\n"
"    margin: 0;\n"
"}")
        self.cadastrar_button.setObjectName("cadastrar_button")
        self.email_person_icon = QtWidgets.QLabel(self.frame)
        self.email_person_icon.setGeometry(QtCore.QRect(310, 170, 20, 20))
        self.email_person_icon.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-pessoa-do-sexo-masculino-100-1.png)\n"
"}\n"
"")
        self.email_person_icon.setText("")
        self.email_person_icon.setObjectName("email_person_icon")
        self.email_div = QtWidgets.QFrame(self.frame)
        self.email_div.setGeometry(QtCore.QRect(300, 170, 1, 20))
        self.email_div.setStyleSheet("Line{\n"
"background: #ccc}")
        self.email_div.setFrameShape(QtWidgets.QFrame.VLine)
        self.email_div.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.email_div.setObjectName("email_div")
        self.senha_div = QtWidgets.QFrame(self.frame)
        self.senha_div.setGeometry(QtCore.QRect(300, 260, 1, 20))
        self.senha_div.setStyleSheet("Line{\n"
"background: #ccc}")
        self.senha_div.setFrameShape(QtWidgets.QFrame.VLine)
        self.senha_div.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.senha_div.setObjectName("senha_div")
        self.senha_icon = QtWidgets.QLabel(self.frame)
        self.senha_icon.setGeometry(QtCore.QRect(310, 260, 20, 20))
        self.senha_icon.setStyleSheet("QLabel{\n"
"background:url(:/login/icons8-cadeado-100.png)\n"
"}\n"
"")
        self.senha_icon.setText("")
        self.senha_icon.setObjectName("senha_icon")
        self.email_text_input.raise_()
        self.fixed_text.raise_()
        self.login_text.raise_()
        self.senha_text_input.raise_()
        self.senha_input.raise_()
        self.esqueceu_senha_text.raise_()
        self.entrar_button.raise_()
        self.cadastrar_button.raise_()
        self.email_input.raise_()
        self.email_person_icon.raise_()
        self.email_div.raise_()
        self.senha_div.raise_()
        self.senha_icon.raise_()
        self.background_blue = QtWidgets.QWidget(Dialog_login)
        self.background_blue.setGeometry(QtCore.QRect(0, 0, 800, 600))
        self.background_blue.setStyleSheet("QWidget{\n"
"background:#0265CB; \n"
"}")
        self.background_blue.setObjectName("background_blue")
        self.background_blue.raise_()
        self.frame.raise_()

        self.retranslateUi(Dialog_login)
        QtCore.QMetaObject.connectSlotsByName(Dialog_login)

    def retranslateUi(self, Dialog_login):
        _translate = QtCore.QCoreApplication.translate
        Dialog_login.setWindowTitle(_translate("Dialog_login", "Dialog"))
        self.fixed_text.setHtml(_translate("Dialog_login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; color:#666666;\">Digite os seus dados nos campos abaixo.</span></p></body></html>"))
        self.login_text.setHtml(_translate("Dialog_login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:20pt; font-weight:696; color:#284658;\">Login</span></p></body></html>"))
        self.email_text_input.setHtml(_translate("Dialog_login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">E-mail</span></p></body></html>"))
        self.email_input.setPlaceholderText(_translate("Dialog_login", "Digite seu e-mail"))
        self.senha_text_input.setHtml(_translate("Dialog_login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; font-weight:696; color:#2d4a5c;\">Senha</span></p></body></html>"))
        self.senha_input.setPlaceholderText(_translate("Dialog_login", "Digite sua senha"))
        self.esqueceu_senha_text.setHtml(_translate("Dialog_login", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'Segoe UI\'; font-size:11pt; text-decoration: underline; color:#939393;\">Esqueci minha senha</span></p></body></html>"))
        self.entrar_button.setText(_translate("Dialog_login", "ENTRAR"))
        self.cadastrar_button.setText(_translate("Dialog_login", "CADASTRAR"))

import telas.login


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_login = QtWidgets.QDialog()
    ui = Ui_Dialog_login()
    ui.setupUi(Dialog_login)
    Dialog_login.show()
    sys.exit(app.exec_())
