# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pagina_inicial.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1020, 601)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setGeometry(QtCore.QRect(0, 50, 1020, 150))
        self.widget_2.setStyleSheet("QWidget{\n"
"background: #03A9F4;\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.nome_tabela_label = QtWidgets.QLabel(self.widget_2)
        self.nome_tabela_label.setGeometry(QtCore.QRect(60, 50, 881, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.nome_tabela_label.setFont(font)
        self.nome_tabela_label.setStyleSheet("QLabel{\n"
"color: #FFFFFF;\n"
"background: #9E9E9E;\n"
"}\n"
"")
        self.nome_tabela_label.setAlignment(QtCore.Qt.AlignCenter)
        self.nome_tabela_label.setObjectName("nome_tabela_label")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 1020, 51))
        self.widget.setStyleSheet("QWidget{\n"
"background:#0265CB\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(20, -1, 20, -1)
        self.horizontalLayout.setSpacing(50)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.config_button_bar_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_button_bar_2.sizePolicy().hasHeightForWidth())
        self.config_button_bar_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.config_button_bar_2.setFont(font)
        self.config_button_bar_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.config_button_bar_2.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 0xp 0px 5px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        self.config_button_bar_2.setIconSize(QtCore.QSize(30, 30))
        self.config_button_bar_2.setObjectName("config_button_bar_2")
        self.horizontalLayout.addWidget(self.config_button_bar_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.config_button_bar = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_button_bar.sizePolicy().hasHeightForWidth())
        self.config_button_bar.setSizePolicy(sizePolicy)
        self.config_button_bar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.config_button_bar.setStyleSheet("QPushButton{\n"
"background:#0265CB;\n"
"border:none;\n"
"padding: 0px 0xp 0px 5px;\n"
"font-size: 16px;\n"
"color: #FFF;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/tool_bar/icons8-configuração-18 (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.config_button_bar.setIcon(icon)
        self.config_button_bar.setIconSize(QtCore.QSize(17, 16))
        self.config_button_bar.setObjectName("config_button_bar")
        self.horizontalLayout.addWidget(self.config_button_bar)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setGeometry(QtCore.QRect(60, 140, 881, 411))
        self.widget_3.setStyleSheet("QWidget{\n"
"background:#F5F5F5;\n"
"border: 1px solid #CCC;\n"
"}")
        self.widget_3.setObjectName("widget_3")
        self.search_icon = QtWidgets.QLabel(self.widget_3)
        self.search_icon.setGeometry(QtCore.QRect(20, 55, 30, 30))
        self.search_icon.setStyleSheet("image: url(:/principal/icons8-pesquisar-20 (1).png);")
        self.search_icon.setText("")
        self.search_icon.setObjectName("search_icon")
        self.buscar_input = QtWidgets.QPushButton(self.widget_3)
        self.buscar_input.setGeometry(QtCore.QRect(490, 20, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buscar_input.setFont(font)
        self.buscar_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buscar_input.setStyleSheet("QPushButton{\n"
"background: #3C4252;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.buscar_input.setCheckable(False)
        self.buscar_input.setAutoExclusive(False)
        self.buscar_input.setObjectName("buscar_input")
        self.editarr_button = QtWidgets.QPushButton(self.widget_3)
        self.editarr_button.setGeometry(QtCore.QRect(699, 12, 171, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.editarr_button.setFont(font)
        self.editarr_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.editarr_button.setStyleSheet("QPushButton{\n"
"background: #03A9F4;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/principal/icons8-soma-20.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.editarr_button.setIcon(icon1)
        self.editarr_button.setIconSize(QtCore.QSize(30, 30))
        self.editarr_button.setObjectName("editarr_button")
        self.search_input = QtWidgets.QPlainTextEdit(self.widget_3)
        self.search_input.setGeometry(QtCore.QRect(50, 55, 421, 30))
        self.search_input.setStyleSheet("QPlainTextEdit{\n"
"font-size:16px;\n"
"background: #FFFFFF;\n"
"border-bottom: 1px solid #999A9A;\n"
"}")
        self.search_input.setObjectName("search_input")
        self.tableWidget_2 = QtWidgets.QTableWidget(self.widget_3)
        self.tableWidget_2.setGeometry(QtCore.QRect(10, 100, 681, 300))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.tableWidget_2.setFont(font)
        self.tableWidget_2.setStyleSheet("QTableWidget{\n"
"background:#FFF;\n"
"border: 1px solid #CCC}")
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(6)
        self.tableWidget_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        self.label = QtWidgets.QLabel(self.widget_3)
        self.label.setGeometry(QtCore.QRect(10, 12, 681, 80))
        self.label.setStyleSheet("QLabel{\n"
"background: #FFF}")
        self.label.setText("")
        self.label.setObjectName("label")
        self.adicionar_aluno_button = QtWidgets.QPushButton(self.widget_3)
        self.adicionar_aluno_button.setGeometry(QtCore.QRect(710, 120, 151, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_aluno_button.setFont(font)
        self.adicionar_aluno_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_aluno_button.setStyleSheet("QPushButton{\n"
"background: #32CD32;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.adicionar_aluno_button.setIcon(icon1)
        self.adicionar_aluno_button.setIconSize(QtCore.QSize(30, 30))
        self.adicionar_aluno_button.setObjectName("adicionar_aluno_button")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(700, 100, 171, 301))
        self.label_2.setStyleSheet("QLabel{\n"
"background: #FFF}")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.adicionar_prof_button = QtWidgets.QPushButton(self.widget_3)
        self.adicionar_prof_button.setGeometry(QtCore.QRect(710, 210, 151, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_prof_button.setFont(font)
        self.adicionar_prof_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_prof_button.setStyleSheet("QPushButton{\n"
"background: #32CD32;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.adicionar_prof_button.setIcon(icon1)
        self.adicionar_prof_button.setIconSize(QtCore.QSize(30, 30))
        self.adicionar_prof_button.setObjectName("adicionar_prof_button")
        self.adicionar_turma_button = QtWidgets.QPushButton(self.widget_3)
        self.adicionar_turma_button.setGeometry(QtCore.QRect(710, 300, 151, 80))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.adicionar_turma_button.setFont(font)
        self.adicionar_turma_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.adicionar_turma_button.setStyleSheet("QPushButton{\n"
"background: #32CD32;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.adicionar_turma_button.setIcon(icon1)
        self.adicionar_turma_button.setIconSize(QtCore.QSize(30, 30))
        self.adicionar_turma_button.setObjectName("adicionar_turma_button")
        self.filtro_comboBox = QtWidgets.QComboBox(self.widget_3)
        self.filtro_comboBox.setGeometry(QtCore.QRect(490, 55, 191, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.filtro_comboBox.setFont(font)
        self.filtro_comboBox.setStyleSheet("QComboBox{\n"
"background: #3C4252;\n"
"color: #FFF;\n"
"border-radius:3px;\n"
"}")
        self.filtro_comboBox.setObjectName("filtro_comboBox")
        self.filtro_comboBox.addItem("")
        self.filtro_comboBox.addItem("")
        self.label_2.raise_()
        self.label.raise_()
        self.search_icon.raise_()
        self.buscar_input.raise_()
        self.editarr_button.raise_()
        self.search_input.raise_()
        self.tableWidget_2.raise_()
        self.adicionar_aluno_button.raise_()
        self.adicionar_prof_button.raise_()
        self.adicionar_turma_button.raise_()
        self.filtro_comboBox.raise_()
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.nome_tabela_label.setText(_translate("MainWindow", "Tabela de Alunos"))
        self.config_button_bar_2.setText(_translate("MainWindow", " Tech School"))
        self.config_button_bar.setText(_translate("MainWindow", "  Configuração"))
        self.buscar_input.setText(_translate("MainWindow", "Buscar"))
        self.editarr_button.setText(_translate("MainWindow", " Editar"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Digite um nome a ser pesquisado"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome completo"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Email"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Cpf"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Periodo"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Disciplina"))
        self.adicionar_aluno_button.setText(_translate("MainWindow", " Aluno"))
        self.adicionar_prof_button.setText(_translate("MainWindow", " Professor"))
        self.adicionar_turma_button.setText(_translate("MainWindow", " Turma"))
        self.filtro_comboBox.setItemText(0, _translate("MainWindow", "Alunos"))
        self.filtro_comboBox.setItemText(1, _translate("MainWindow", "Professores"))
import principal_rc
import toolBar_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
